name: pwc-feed Actions
on: 
  push:
  schedule:
    - cron: '0 9 * * *'

jobs:
  my-job:
    name: update_rss_feeds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        chmod -R 777 ./log/log |
        chmod -R 777 ./rss

    - name: setup python
      uses: 
        actions/setup-python@v3
      with:
        python-version: "3.9"

    # error starting here
    - name: install dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: update feeds
      run: |
          python ./feed.py>>./log/log

