name: pwc-feed Actions
on: 
  push:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'

jobs:
  my-job:
    name: update rss_
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        chmod -R 777 ./log/log |
        chmod -R 777 ./rss

    - name: setup python
      uses: 
        actions/setup-python@v3
      with:
        python-version: "3.9"

    # error starting here
    - name: install dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: update feeds
      run: |
          python ./feed.py>>./log/log
    
    # https://github.community/t/possible-to-commit-files-after-workflow-runs/17824
    - name: Commit files
      run: |
        git config --local user.email "taobot@github.com"
        git config --local user.name "my_commit_bot"
        git add ./log/log
        git add ./rss
        git commit -m "Add changes"

    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
