name: pwc-feed Actions
on: 
  push:
  schedule:
    - cron: '0 9 * * *'

jobs:
  my-job:
    name: update_rss_feeds
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # - name: install dependency
    #   uses: s-weigand/setup-conda@v1
    #   run: |
    #       python -m pip install --upgrade pip
    #       conda env update --file ./req/environment.yml --name base

    # - name: update feeds
    #       python feed.py>>./log/log

